name: Terraform AWS Provisioning with Terraform Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: dev

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESSKEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET}}
      AWS_DEFAULT_REGION: ${{ secrets.REGION}}
      TF_CLOUD_ORGANIZATION: Cloudwitch
      TF_WORKSPACE: terraform-aws
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

    #   - name: Terraform Apply
    #     run: terraform apply -auto-approve
    #     if: github.ref == 'refs/heads/main'
